name: Deploy Passworld

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses actions/checkout@v2

      - name: Compile CSS and Javascript
        run: |
          npm install
          npm run prod

      - name: Configure PHP 8.0
        php-version: 8.0
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml


